// パチュリー（ノーマル）
constexpr int ROUND_BULLETCOUNT_T_NORMAL_PATCHOULI = 8;
constexpr int EVERYDIRECTION_BULLETCOUNT_T_NORMAL_PATCHOULI = 192;
// パチュリー（メタル・ファティーグ）
constexpr int EVERYDIRECTION_BULLETCOUNT_T_METALFATIGUE_PATCHOULI = 8;
constexpr int SPLITONE_INTOEIGHT_BULLETCOUNT_T_METALFATIGUE_PATCHOULI = 64;
// パチュリー（サイレント・セレナ）
constexpr int CIRCLECONTIGUOUS_BULLETCOUNT_T_SILENTSERENA_PATCHOULI = 320;
constexpr int SLOWLYCOMING_BULLETCOUNT_T_SILENTSERENA_PATCHOULI = 180;


// チルノ（ノーマル）
constexpr int STRAIGHTAPPROACH_BULLETCOUNT_T_NORMAL_CIRNO = 81;
constexpr int EVERYDIRECTION_BULLETCOUNT_T_NORMAL_CIRNO = 112;
// チルノ（アイシクル・フォール）
constexpr int SHOTOUTERMOVEINNER_BULLETCOUNT_T_ICICLEFALL_CIRNO = 120;
constexpr int LINEUPSTRAIGHTSHOT_BULLETCOUNT_T_ICICLEFALL_CIRNO = 15;
// チルノ（パーフェクト・フリーズ）
constexpr int CIRCLECONTIGUOUS_BULLETCOUNT_T_PERFECTFREEZE_CIRNO = 300;
constexpr int EXPANDSTRAIGHTSHOT_BULLETCOUNT_T_PERFECTFREEZE_CIRNO = 120;


// 諏訪子（ノーマル）
constexpr int CIRCLECONTIGUOUS_BULLETCOUNT_T_NORMAL_SUWAKO = 280;
// 諏訪子（洩矢の鉄の輪）
constexpr int SLOWLYCOMING_BULLETCOUNT_T_IRONRINGOFMORIYA_SUWAKO = 900;
// 諏訪子（ケロちゃん風雨に負けず）
constexpr int STRAIGHTAPPROACH_BULLETCOUNT_T_KCSTANDSFIRMAGAINSTSTORM_SUWAKO = 200;
constexpr int FALLINGAPPROACH_BULLETCOUNT_T_KCSTANDSFIRMAGAINSTSTORM_SUWAKO = 300;